import type { CompareSource, CompareRow, CompareGroup, CompareConclusionRow } from "@/types/vietlicense";

export const compareSources: CompareSource[] = [
  {
    id: "nv",
    initials: "NV",
    name: "Niềm Vui Nhỏ",
    category: "very-low",
    categoryLabel: "Giá rất thấp",
    productName: "Office 2021 Pro Plus No Box",
    summary: "Thấp hơn, thiếu hồ sơ",
    evidenceLabel: "Giá họ",
    evidenceText: "99.000đ",
    note:
      "Key-only/forum/marketplace; chưa thấy VAT & hồ sơ doanh nghiệp rõ. Phù hợp nhóm vài chục đến vài trăm nghìn; rủi ro cần kiểm tra là chứng từ, đối tượng sử dụng và tính tương đồng SKU.",
    href: "https://niemvainuocmam.com/",
    imageAlt: "Shop Niềm Vui Nhỏ",
  },
  {
    id: "sp",
    initials: "SP",
    name: "Marketplace Shopee mẫu",
    category: "very-low",
    categoryLabel: "Giá rất thấp",
    productName: "Office 2021 Pro Plus No Box",
    summary: "Thấp hơn, thiếu hồ sơ",
    evidenceLabel: "Giá họ",
    evidenceText: "199.999đ đến 200.000đ",
    note:
      "Marketplace nhiều người bán; giá và chứng từ phụ thuộc từng shop, chưa thấy VAT/hợp đồng doanh nghiệp rõ ở listing mẫu. Dùng làm benchmark sàn giá rẻ, không dùng làm đối thủ cùng chuẩn chứng từ.",
    href: "https://shopee.vn/",
    imageAlt: "Shopee Microsoft 365 listings",
  },
  {
    id: "voz",
    initials: "VOZ",
    name: "VOZ / KeyNgon",
    category: "very-low",
    categoryLabel: "Giá rất thấp",
    productName: "Office 2021 Pro Plus No Box",
    summary: "Thấp hơn, thiếu hồ sơ",
    evidenceLabel: "Giá họ",
    evidenceText: "239.000đ Office; 79.000đ Windows",
    note:
      "Forum/key-only; chưa thấy VAT, hợp đồng, fullbox hoặc bàn giao doanh nghiệp rõ trên nguồn này. Giá rất thấp so với mốc VietLicense; dùng để nhận diện phân khúc key-only/forum.",
    href: "https://voz.vn/",
    imageAlt: "VOZ KeyNgon",
  },
  {
    id: "bt",
    initials: "BT",
    name: "BotayIT",
    category: "very-low",
    categoryLabel: "Giá rất thấp",
    productName: "Office 2021 Pro Plus No Box",
    summary: "Thấp hơn, thiếu hồ sơ",
    evidenceLabel: "Giá họ",
    evidenceText: "300.000đ",
    note:
      "Key-only; chưa thấy fullbox/no-box VietLicense-equivalent, VAT/hợp đồng rõ trên trang sản phẩm. Giá thấp hơn rất sâu; nên tư vấn khách kiểm tra phạm vi bảo hành, chứng từ và cách kích hoạt trước khi so giá.",
    href: "https://botayit.com/",
    imageAlt: "BotayIT Office 2021 Pro Plus",
  },
  {
    id: "h2",
    initials: "H2",
    name: "H2ShopTech",
    category: "vat-bulk",
    categoryLabel: "VAT/sỉ",
    productName: "Windows 10/11 DVD Fullbox",
    summary: "Cao hơn VietLicense",
    evidenceLabel: "Giá họ",
    evidenceText: "1.800.000đ",
    note:
      "Trang nêu hỗ trợ xuất VAT; tình trạng hết hàng. SKU gần nhóm DVD/full VAT nhưng nguồn đang hết hàng; giá niêm yết cao hơn VietLicense.",
    href: "https://h2shoptech.com/",
    imageAlt: "H2ShopTech Windows 11 Pro DSP OEI DVD Full VAT",
  },
  {
    id: "it",
    initials: "IT",
    name: "ITSO / Tin Học Nguyễn Tài",
    category: "vat-bulk",
    categoryLabel: "VAT/sỉ",
    productName: "Office 2021 Pro Plus Fullbox",
    summary: "Cao hơn VietLicense",
    evidenceLabel: "Giá họ",
    evidenceText: "2.700.000đ",
    note:
      "Full VAT trong tiêu đề/mô tả; trang còn hàng tại thời điểm kiểm tra. Cùng kiểu nhất với mốc Office 2021 Fullbox; VietLicense rẻ hơn vừa phải.",
    href: "https://itsogroup.com/",
    imageAlt: "ITSO Office 2021 Pro Plus Full Box Full VAT",
  },
  {
    id: "wb",
    initials: "WB",
    name: "WinBanQuyen BIG SOFT",
    category: "vat-bulk",
    categoryLabel: "VAT/sỉ",
    productName: "Office 2021 Pro Plus Fullbox",
    summary: "Cao hơn VietLicense",
    evidenceLabel: "Giá họ",
    evidenceText: "3.199.000đ",
    note:
      "Có thông tin công ty và full VAT trên trang sản phẩm. Cùng nhóm có chứng từ; VietLicense thấp hơn rõ ở Office 2021 Fullbox.",
    href: "https://winbanquyen.com/",
    imageAlt: "WinBanQuyen Office 2021 Fullbox Full VAT",
  },
  {
    id: "sbq",
    initials: "SBQ",
    name: "ShopBanQuyen / BQ Digital",
    category: "vat-bulk",
    categoryLabel: "VAT/sỉ",
    productName: "Office 2021 Pro Plus Fullbox",
    summary: "Cao hơn VietLicense",
    evidenceLabel: "Giá họ",
    evidenceText: "4.800.000đ",
    note:
      "Trang nêu VAT, giấy chứng nhận, bán sỉ, báo giá, hợp đồng, hóa đơn. Cùng kiểu chứng từ/sỉ; giá đối thủ cao hơn hơn 2 lần so với VietLicense cho SKU gần nhất.",
    href: "https://shopbanquyen.com/",
    imageAlt: "ShopBanQuyen Office 2021 Fullbox",
  },
  {
    id: "fps",
    initials: "FPS",
    name: "FPS Vietnam",
    category: "vat-bulk",
    categoryLabel: "VAT/sỉ",
    productName: "Windows 10/11 FPP USB Fullbox",
    summary: "Cao hơn VietLicense",
    evidenceLabel: "Giá họ",
    evidenceText: "4.900.000đ",
    note:
      "Trang ghi đã có VAT. Cùng nhóm FPP USB có VAT; VietLicense thấp hơn rất mạnh.",
    href: "https://fps.com.vn/",
    imageAlt: "FPS Windows 11 Pro FPP USB",
  },
  {
    id: "sv",
    initials: "SV",
    name: "SoftVN",
    category: "vat-bulk",
    categoryLabel: "VAT/sỉ",
    productName: "Microsoft 365 Business Standard",
    summary: "Cần kiểm điều kiện",
    evidenceLabel: "Giá họ",
    evidenceText: "2.850.000đ/năm",
    note:
      "Trang có báo giá, ưu đãi mua số lượng lớn và xuất hóa đơn VAT đầy đủ. Đối thủ thấp hơn VietLicense ở M365 Standard; cần kiểm tra điều kiện số lượng, thời hạn và VAT khi chốt deal.",
    href: "https://softvn.com/",
    imageAlt: "SoftVN Microsoft 365 Business Standard",
  },
  {
    id: "mb",
    initials: "MB",
    name: "Mắt Bão",
    category: "vat-bulk",
    categoryLabel: "VAT/sỉ",
    productName: "Microsoft 365 Business Standard",
    summary: "Cần kiểm điều kiện",
    evidenceLabel: "Giá họ",
    evidenceText: "265.000đ/user/tháng, tương đương 3.180.000đ/năm",
    note:
      "Có chương trình ưu đãi đến 30/06/2026; có gói theo user/tháng. Giá gần VietLicense, thấp hơn nhẹ theo niêm yết tháng; cần kiểm tra VAT và điều kiện khuyến mãi khi báo khách.",
    href: "https://matbao.vn/",
    imageAlt: "Mắt Bão Office 365",
  },
  {
    id: "ad",
    initials: "AD",
    name: "Adtimin",
    category: "vat-bulk",
    categoryLabel: "VAT/sỉ",
    productName: "Microsoft 365 Business Standard",
    summary: "Cần kiểm điều kiện",
    evidenceLabel: "Giá họ",
    evidenceText: "3.228.000đ/năm",
    note:
      "Trang bảng giá ghi các mức giá đã bao gồm VAT và khuyến nghị liên hệ để báo giá chính xác. M365 Standard rất gần giá VietLicense; đối thủ thấp hơn nhẹ theo giá đăng ký mới tại thời điểm kiểm tra.",
    href: "https://adtimin.vn/",
    imageAlt: "Adtimin bảng giá Microsoft 365",
  },
  {
    id: "cps",
    initials: "CPS",
    name: "CellphoneS",
    category: "retail",
    categoryLabel: "Retail chính ngạch",
    productName: "Microsoft 365 Business Standard",
    summary: "Cần kiểm điều kiện",
    evidenceLabel: "Giá họ",
    evidenceText: "Liên hệ / sắp về hàng",
    note:
      "Trang ghi chính hãng/xuất VAT nhưng trạng thái liên hệ/sắp về hàng. Đủ làm nguồn retail/chính ngạch, nhưng không dùng để tính chênh lệch giá vì thiếu giá niêm yết.",
    href: "https://cellphones.com.vn/",
    imageAlt: "CellphoneS Microsoft 365 Business Standard",
  },
  {
    id: "mso",
    initials: "MSO",
    name: "MSO.vn",
    category: "retail",
    categoryLabel: "VAT/sỉ",
    productName: "Microsoft 365 Business Basic",
    summary: "Benchmark đối tác",
    evidenceLabel: "Giá họ",
    evidenceText: "89.000đ/user/tháng, tương đương 1.068.000đ/năm",
    note:
      "Trang định vị đối tác Microsoft; cần kiểm tra VAT/Teams/điều kiện theo plan cụ thể. Đối thủ thấp hơn ở Business Basic; khi so sánh cần nói rõ có/không Teams và điều kiện hóa đơn.",
    href: "https://mso.vn/",
    imageAlt: "MSO Microsoft 365 Business Basic",
  },
  {
    id: "ps",
    initials: "PS",
    name: "Pacisoft",
    category: "retail",
    categoryLabel: "VAT/sỉ",
    productName: "Windows 10/11 FPP USB Fullbox",
    summary: "Benchmark đối tác",
    evidenceLabel: "Giá họ",
    evidenceText: "4.599.000đ",
    note:
      "Trang thể hiện đối tác/đại lý Microsoft, Full VAT và giá số lượng lớn. Cùng nhóm bán bản quyền có VAT/sỉ; VietLicense thấp hơn khoảng một nửa ở Windows FPP.",
    href: "https://pacisoft.vn/",
    imageAlt: "Pacisoft Windows 10/11 FPP USB Full VAT",
  },
  {
    id: "fpt",
    initials: "FPT",
    name: "FPT Shop",
    category: "retail",
    categoryLabel: "Retail chính ngạch",
    productName: "Microsoft 365 Business Standard",
    summary: "Retail cao",
    evidenceLabel: "Giá họ",
    evidenceText: "3.890.000đ/năm",
    note:
      "Retail lớn; tên URL cũ nhưng trang hiển thị Business Standard tại thời điểm kiểm tra. Cùng SKU M365 Standard gần nhất; VietLicense thấp hơn khoảng 18%.",
    href: "https://fptshop.com.vn/",
    imageAlt: "FPT Shop Microsoft 365 Business Standard",
  },
  {
    id: "pv",
    initials: "PV",
    name: "Phong Vũ",
    category: "retail",
    categoryLabel: "Retail chính ngạch",
    productName: "Windows 10/11 FPP USB Fullbox",
    summary: "Retail cao",
    evidenceLabel: "Giá họ",
    evidenceText: "5.090.000đ",
    note:
      "Retail lớn; trang có trạng thái liên hệ/số lượng theo thời điểm kiểm tra. Cùng nhóm FPP USB retail; giá cao hơn VietLicense hơn 2 lần.",
    href: "https://phongvu.vn/",
    imageAlt: "Phong Vũ Windows 11 Pro FPP USB",
  },
  {
    id: "ms",
    initials: "MS",
    name: "Microsoft Store",
    category: "retail",
    categoryLabel: "Retail chính ngạch",
    productName: "Office 2021 Pro Plus Fullbox",
    summary: "Retail cao",
    evidenceLabel: "Giá họ",
    evidenceText: "7.899.000đ",
    note:
      "Microsoft Store chính hãng; SKU khác edition và đời sản phẩm. Mốc retail chính ngạch rất cao, nhưng khác Office Pro Plus 2021 nên chỉ dùng để định vị dải giá chính hãng.",
    href: "https://www.microsoft.com/",
    imageAlt: "Microsoft Office Home & Business 2024",
  },
  {
    id: "hc",
    initials: "HC",
    name: "HACOM",
    category: "retail",
    categoryLabel: "Retail chính ngạch",
    productName: "Office 2021 Pro Plus Fullbox",
    summary: "Retail cao",
    evidenceLabel: "Giá họ",
    evidenceText: "9.699.000đ",
    note:
      "Trang ghi giá đã bao gồm VAT; retail chính ngạch giá cao. Giá retail rất cao so với mốc VietLicense, nhưng edition/hình thức key điện tử không trùng tuyệt đối.",
    href: "https://hacom.vn/",
    imageAlt: "HACOM Office Professional 2021",
  },
];

export const compareRows: CompareRow[] = [
  {
    competitor: "Niềm Vui Nhỏ",
    theirPrice: "99.000đ",
    vietLicensePrice: "2.150.000đ từ 5 bản",
    skuNote: "SKU tham chiếu",
    signal: "Thấp hơn, thiếu hồ sơ",
    position: "Nguồn",
  },
  {
    competitor: "Marketplace Shopee mẫu",
    theirPrice: "199.999đ đến 200.000đ",
    vietLicensePrice: "2.150.000đ từ 5 bản",
    skuNote: "SKU tham chiếu",
    signal: "Thấp hơn, thiếu hồ sơ",
    position: "Nguồn",
  },
  {
    competitor: "VOZ / KeyNgon",
    theirPrice: "239.000đ Office; 79.000đ Windows",
    vietLicensePrice: "2.150.000đ từ 5 bản",
    skuNote: "SKU tham chiếu",
    signal: "Thấp hơn, thiếu hồ sơ",
    position: "Nguồn",
  },
  {
    competitor: "BotayIT",
    theirPrice: "300.000đ",
    vietLicensePrice: "2.150.000đ từ 5 bản",
    skuNote: "SKU tham chiếu",
    signal: "Thấp hơn, thiếu hồ sơ",
    position: "Nguồn",
  },
  {
    competitor: "WebBanQuyen low-price listings",
    theirPrice: "519.000đ Office; 350.000đ Windows",
    vietLicensePrice: "1.400.000đ từ 5 bản",
    skuNote: "SKU tham chiếu",
    signal: "Thấp hơn, thiếu hồ sơ",
    position: "Nguồn",
  },
  {
    competitor: "H2ShopTech",
    theirPrice: "1.800.000đ",
    vietLicensePrice: "1.200.000đ từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cao hơn VietLicense",
    position: "Nguồn",
  },
  {
    competitor: "ITSO / Tin Học Nguyễn Tài",
    theirPrice: "2.700.000đ",
    vietLicensePrice: "2.550.000đ từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cao hơn VietLicense",
    position: "Nguồn",
  },
  {
    competitor: "WinBanQuyen BIG SOFT",
    theirPrice: "3.199.000đ",
    vietLicensePrice: "2.550.000đ từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cao hơn VietLicense",
    position: "Nguồn",
  },
  {
    competitor: "ShopBanQuyen / BQ Digital",
    theirPrice: "4.800.000đ",
    vietLicensePrice: "2.550.000đ từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cao hơn VietLicense",
    position: "Nguồn",
  },
  {
    competitor: "FPS Vietnam",
    theirPrice: "4.900.000đ",
    vietLicensePrice: "2.550.000đ từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cao hơn VietLicense",
    position: "Nguồn",
  },
  {
    competitor: "SoftVN",
    theirPrice: "2.850.000đ/năm",
    vietLicensePrice: "3.290.000đ/năm từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cần kiểm điều kiện",
    position: "Nguồn",
  },
  {
    competitor: "Mắt Bão",
    theirPrice: "265.000đ/user/tháng, tương đương 3.180.000đ/năm",
    vietLicensePrice: "3.290.000đ/năm từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cần kiểm điều kiện",
    position: "Nguồn",
  },
  {
    competitor: "Adtimin",
    theirPrice: "3.228.000đ/năm",
    vietLicensePrice: "3.290.000đ/năm từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cần kiểm điều kiện",
    position: "Nguồn",
  },
  {
    competitor: "CellphoneS",
    theirPrice: "Liên hệ / sắp về hàng",
    vietLicensePrice: "3.290.000đ/năm từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Cần kiểm điều kiện",
    position: "Nguồn",
  },
  {
    competitor: "MSO.vn",
    theirPrice: "89.000đ/user/tháng, tương đương 1.068.000đ/năm",
    vietLicensePrice: "1.290.000đ/năm từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Benchmark đối tác",
    position: "Nguồn",
  },
  {
    competitor: "Pacisoft",
    theirPrice: "4.599.000đ",
    vietLicensePrice: "2.550.000đ từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Benchmark đối tác",
    position: "Nguồn",
  },
  {
    competitor: "FPT Shop",
    theirPrice: "3.890.000đ/năm",
    vietLicensePrice: "3.290.000đ/năm từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Retail cao",
    position: "Nguồn",
  },
  {
    competitor: "Phong Vũ",
    theirPrice: "5.090.000đ",
    vietLicensePrice: "2.550.000đ từ 5 bản",
    skuNote: "SKU gần/trùng",
    signal: "Retail cao",
    position: "Nguồn",
  },
  {
    competitor: "Microsoft Store",
    theirPrice: "7.899.000đ",
    vietLicensePrice: "2.550.000đ từ 5 bản",
    skuNote: "SKU tham chiếu",
    signal: "Retail cao",
    position: "Nguồn",
  },
  {
    competitor: "HACOM",
    theirPrice: "9.699.000đ",
    vietLicensePrice: "2.550.000đ từ 5 bản",
    skuNote: "SKU tham chiếu",
    signal: "Retail cao",
    position: "Nguồn",
  },
];

export const compareGroups: CompareGroup[] = [
  {
    heading: "Giá rất thấp",
    subheading: "5 nguồn",
    body: "Thường là key-only, forum, marketplace hoặc chưa thấy VAT/hợp đồng/bàn giao doanh nghiệp rõ trên nguồn công khai.",
    ctaLabel: "Xem bằng chứng 20 nguồn",
    ctaHref: "#bang-bang-chung",
  },
  {
    heading: "Có chứng từ / retail",
    subheading: "15 nguồn",
    body: "Nhiều SKU có VAT/retail cao hơn VietLicense; trường hợp giá gần hoặc thấp hơn cần kiểm tra điều kiện VAT, Teams, khuyến mãi và số lượng.",
    ctaLabel: "Xem bằng chứng 20 nguồn",
    ctaHref: "#bang-bang-chung",
  },
];

export const compareConclusionRows: CompareConclusionRow[] = [
  {
    choice: "Chọn giá rất thấp",
    price: "Rẻ hơn rất sâu",
    vatNote: "Thường chưa thấy đủ VAT, hợp đồng hoặc bàn giao doanh nghiệp trên nguồn công khai.",
    conclusion: "Chỉ hợp khi bạn chấp nhận tự kiểm tra toàn bộ chứng từ và rủi ro SKU.",
  },
  {
    choice: "Chọn VietLicense",
    price: "Giá ở giữa",
    vatNote: "Có tư vấn đúng SKU, VAT theo yêu cầu, hỗ trợ kích hoạt và hồ sơ Microsoft Marketplace.",
    conclusion: "Lựa chọn cân bằng cho cá nhân nghiêm túc và doanh nghiệp cần lưu hồ sơ.",
  },
  {
    choice: "Chọn retail/chứng từ cao",
    price: "Thường cao hơn",
    vatNote: "Chứng từ hoặc thương hiệu retail rõ hơn, nhưng giá nhiều SKU cao hơn VietLicense.",
    conclusion: "Phù hợp khi bạn ưu tiên kênh retail lớn và chấp nhận ngân sách cao hơn.",
  },
];
